### ISSUE TITLE
Form alias not available

### ISSUE THREAD

**Issue by jeronert** [Pixelindustries/elegant-asgard#17]
Temporary solution is to add Pingpong\Menus\MenusServiceProvider to your app/config.php aliases.
It should register these aliases somewhere else I suppose :)

**Comment by mvdstam** [comment]
Not an Elegant-Asgard issue, since the `Form` alias is used within Asgard itself as well. I believe this to be fixed as of the latest AsgardCMS version anyway; if you do a fresh install of Asgard and pull in Elegant, everything works as intended regarding the usage of `Form`.
